name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Test:
    name: Unit Test
    strategy:
      matrix:
        go-version: [1.22.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Test
        run: |
          go test -v ./...
